php-twinfield/twinfield

- src/DomDocuments/CustomersDocument.php
- tests/IntegrationTests/resources/customerSendRequest.xml
if you don’t specify a < code > element, twinfield will automatically generate a new code according to the administration it’s mask. If you specify < code > Twinfield will actually say that code is required. If you don't pass in the element at all the code will be automatically generated.
getFirstFreeCode is unreliable as administrations can use different masks. It will also not work on administration with multiple (legacy) ranges
I have a lot of fixes and new functionalities for this library. I also improved the OAuth library because right now it is dependant on a $_SESSION. If you use something else for your intermediate token storage (for instance a framework for session management) this won't work
Also you maybe should remove the password authentication part from the documentation …
> don’t create empty elements

- src/DomDocuments/InvoicesDocument.php
- src/InvoiceLine.php
- src/Mappers/InvoiceMapper.php
- tests/IntegrationTests/resources/invoiceSendRequest.xml
Adds the attribute performanceType for InvoiceLines as documented: https://c3.twinfield.com/webservices/documentation/#/ApiReference/SalesInvoices
Copied over from our [fork](https://github.com/picqer/twinfield-php-client/commit/32a6a859f9e1a21e7b05e6b302157751254300b2) which we are already using for quite some time and will abandon when this one is up to speed :)
> Adds performanceType to SalesInvoiceLines

- src/DomDocuments/BaseDocument.php
- src/DomDocuments/CustomersDocument.php
- tests/IntegrationTests/resources/customerSendRequest.xml
- tests/UnitTests/DomDocuments/CustomersDocumentUnitTest.php
The `CustomerApiConnector::sendAll()` was broken because `CustomersDocument` has an implementation that only supported once customer.
This resulted in always having 1 `<dimension>` element with duplicate info for all customers (e.g. calling `$document->addCustomer($customer)` 20 times would result in 20 `<code>` elements, etc.
> Fix customers send all

- src/Mappers/BankTransactionMapper.php
- tests/UnitTests/ApiConnectors/BankTransactionApiConnectorTest.php
- tests/UnitTests/ApiConnectors/resources/banktransaction-with-all-line-types.xml
Some fields could not be parsed, as they are not part of the `BankTransactionLine` classes. Examples of such fields are `currencydate` and `basevalue`.
~~Furthermore, no example XML line for the VAT type is available, so no tests have been added for the parsing of such lines.~~ This has now been fixed, given that a new example XML response containing all line types has been provided by @Daanvm.
This PR fixes #71.
> Added support for parsing the lines in BankTransactions.

- src/ApiConnectors/BankTransactionApiConnector.php
- src/ApiConnectors/CustomerApiConnector.php
- src/ApiConnectors/TransactionApiConnector.php
- src/Response/IndividualMappedResponse.php
- src/Response/MappedResponseCollection.php
- src/Services/ProcessXmlService.php
- tests/UnitTests/Request/MappedResponseCollectionUnitTest.php
Instead of stopping as soon as an object contains an error, now all objects that are returned by Twinfield will be processed. All `IndividualMappedResponse` objects will furthermore be wrapped into a `MappedResponseCollection` object. This class has methods to easily determine whether the objects returned by Twinfield have errors/are successful, how many of them have errors/are successful and return the `IndividualMappedResponse` objects that have errors/are successful.
This PR fixes #73.
> Added support for processing all objects when using 'sendAll()'.

- src/ApiConnectors/BaseApiConnector.php
- src/Services/ProcessXmlService.php
- tests/UnitTests/ApiConnectors/BaseApiConnectorTest.php
This Pull Request fixes #76 by adding the functionality of automatically retrying request in case of the specified SSL error. It will retry a maximum of three times (defined by a constant), after which it will throw an exception anyway.
Because the amount of error messages that we want to retry automatically might increase in the future, I figured I could best create a constant array with these messages, such that the logic of checking whether the request should be retried can be embedded in a for-loop. Thankfully, PHP 7.1 features catching multiple exception class in one catch block, which prevented the need for duplicating code.
I furthermore modified the `\PhpTwinfield\UnitTests\BaseApiConnectorTest` to work for both the SoapFault and ErrorException exception types, and for all error …
> Added support for retrying requests that return the SSL error.

- readme.md
- src/Secure/OpenIdConnectAuthentication.php
- tests/UnitTests/Secure/OpenIdConnectionAuthenticationTest.php
This PR improves the implementation of OAuth2 authentication.
Previously, an `\League\OAuth2\Client\Token\AccessToken` was expected when creating an instance of the `\PhpTwinfield\Secure\OpenIdConnectAuthentication` class. This `AccessToken` has to contain an access token.
The problem is that only providing a refresh token is enough, as a valid access token can be retrieved using the refresh token. This has now been implemented in the code.
> Require only a refresh token for OAuth2 authentication

- src/Secure/Provider/OAuthProvider.php
- src/Secure/Provider/ResourceOwner.php
- tests/UnitTests/Secure/Provider/OAuthProviderTest.php
After some communication with Twinfield, it became apparent that the `twf.user` scope was not working, because the `openid` scope was missing. Unfortunately, this was not stated in their documentation (which will be updated). Furthermore, the problem with the `getResourceOwner` method is fixed. It can be called only when the `openid` scope is used. The `twf.user` scope can optionally be passed to retrieve more information from the `getResourceOwner` method.
Changes:
- Added the `openid` scope as constant.
- Added the `openid` scope as a default scope, as the default scopes should include those scopes that are necessary to request the details of the resource owner.
- Made sure to allow the `twf.user` scope again, but only if the `openid` scope is present.
- Modified the `ResourceOwner` …
> Fix for the 'twf.user' scope and 'getResourceOwner' method

- src/MatchLine.php
As the title states, this PR fixes the `\PhpTwinfield\MatchLine::getWriteOffType` return type.
Furthermore, removed some unnecessary/redundant information from docblocks. No change is required in `\PhpTwinfield\DomDocuments\MatchDocument::createLineElement` (where the method is being used), because when `\PhpTwinfield\MatchLine::$writeoff` is non-null, it is guaranteed that `\PhpTwinfield\MatchLine::$writeofftype` is non-null.
This PR fixes #82.
> Fix 'getWriteOffType' return type

- src/BookingReference.php
- src/BookingReferenceInterface.php
- src/MatchReference.php
- src/MatchReferenceInterface.php
- tests/UnitTests/BookingReferenceUnitTest.php
- tests/UnitTests/MatchReferenceUnitTest.php
Deleting transactions, statements, etc. is done using a reference to
that object. However, the existing `MatchReferenceInterface` does not
suffice for this, since it references a specific line within such an
object.
Therefore `BookingReferenceInterface` was added to unqiuely identify a
booking.
`BookingReferenceInterface` is not extended by `MatchReferenceInterface`
on purpose, since we don't want anyone to accidentally pass a
`MatchReferenceInterface` to a delete method, expecting the specific
line to be deleted, but it actually deletes the entire transaction.
Usage of `BookingReferenceInterface` should be explicit.
Ease of use methods `BookingReference::fromMatchReference()` and
`MatchReference::fromBookingReference()` have been added.
> Add `BookingReferenceInterface` for identifying bookings

- composer.json
- src/ApiConnectors/BaseApiConnector.php
- src/Util.php
- tests/UnitTests/ApiConnectors/BaseApiConnectorTest.php
I've added logging to the `BaseApiConnector` so that it becomes possible to debug the actual requests and responses send and received from Twinfield.
> Add psr/log and have `BaseApiConnector` log info, debug and error logs

- src/ApiConnectors/BankTransactionApiConnector.php
- src/Mappers/BankTransactionMapper.php
- tests/UnitTests/ApiConnectors/BankTransactionApiConnectorTest.php
- tests/UnitTests/ApiConnectors/resources/failed-response-without-line-ids.xml
When a bank transaction fails to be created for whatever reason,
Twinfield does not generate an ID for the lines in the bank transaction,
so when mapping the response we should not require them to be set.
> Make sure we can map bank transactions without line ids

- src/BaseTransactionLine.php
- src/DomDocuments/TransactionsDocument.php
- src/Transactions/BankTransactionLine/Base.php
- src/Transactions/TransactionLineFields/FreeCharField.php
If line type is total and filled with N the sales invoice is excluded from direct debit runs done in Twinfield.
> Added support for Free character field

- src/DomDocuments/BaseDocument.php
There seems to be a small copy-paste error in the $object->getFreetextX() which results that the getFreetext() don't match with the statement below.
> Fix typo's in getFreetext()

- src/CustomerAddress.php
- src/CustomerBank.php
- src/DomDocuments/CustomersDocument.php
- src/Mappers/CustomerMapper.php
- tests/IntegrationTests/CustomerIntegrationTest.php
- tests/UnitTests/DomDocuments/CustomersDocumentUnitTest.php
Twinfield expects string representation of boolean ("true"/"false") instead of 1 or 0 for "default" attribute in XML for customer address and customer bank element.
> Twinfield expects string representation of boolean ("true"/"false")

- src/Secure/Provider/OAuthProvider.php
Added the offline_access and organisation scopes to the array of default scopes in order to receive a refresh token and the cluster URL respectively, according to the [Twinfield documentation](https://c3.twinfield.com/webservices/documentation/#/ApiReference/Authentication/OpenIdConnect).
Closes #125
> Add offline_access and organisation scopes

- src/ApiConnectors/OfficeApiConnector.php
When there is exactly one office being returned the variable $officeArray is an array, not an object.
> Added type check for handling officeArray

- src/Secure/WebservicesAuthentication.php
When using the webservice authenticator in a queue runner I often receive the error "Your logon credentials are not valid anymore. Try to log on again.". There is a catch in BaseApiConnector::sendXmlDocument which retries the request with a fresh connection, but this fresh connection doesn't log on again. This means the error keeps happening.
I added the resetClient and resetAllClients methods to the WebservicesAuthentication class to reset the sessionID before resetting the connection resulting in a fresh login.
> Reset login when resetting webservice connection

- src/ApiConnectors/BrowseDataApiConnector.php
- src/Mappers/BrowseDataMapper.php
- src/Util.php
When Twinfield returns an empty date it should be converted to NULL.
> Optional date time patch

- src/Enums/BrowseColumnOperator.php
Twinfield seems to return this operator when querying the browse definition for `130_2` (Customers v2)
Code to reproduce:
```php
$connector = new BrowseDataApiConnector(...);
$connector->->getBrowseDefinition('130_2');
```
> Add like browse column operator

- src/Mappers/BrowseDataMapper.php
- src/Util.php
Right now querying nullable dates from the browse API will cause an exception, in my case the matchdate on Supplier transactions (code 200)
The next line of code will cause an exception:
```php
(new BrowseColumn)->setField('fin.trs.line.matchdate')->setVisible(true),
```
Exception: `Invalid date, expected in yyyymmdd format, got "".`
With this PR no exception is thrown and a `BrowseDataCell` with value `null` is returned instead
I opted to not change the Util::parseDate and parseDateTime methods themselves, because they are used in other places as well.
> Allow dates from Browse data to be null

- src/BaseObject.php
This prevents a `count(): Parameter must be an array or an object that implements Countable` warning on PHP 7.2 and above.
> Change $messages default value to an empty array

- src/DomDocuments/SuppliersDocument.php
Address default attribute requires a string value of `true` or `false`. Currently booleans are converted to `0` or `1` when building the xml which makes the request fail.
> Fixing issue where default was converted to 0 or 1 in the xml

- src/Mappers/TransactionMapper.php
Transactions sometimes have `<line>` elements that are not actually transaction lines (e.g. match lines), these lines will break the mapper as it tries to map them because information is missing.
By using a XPath we only iterate over the `<line>` elements that are actually transaction lines
Closes #168
> Fix TransactionMapper to ignore 'line' elements that are not actually transaction lines

- src/DomDocuments/TransactionsDocument.php
When sending a custom transaction to Twinfield (one that extends one of the package transactions and doesn't directly use package traits), invoice number and payment reference will be skipped even if they are present. This PR fixes that by using the utility that already exists within the package.
The mapper side of things seems to be unaffected as it already uses this utility.
> Allow custom transaction classes to use invoice number and payment reference

- src/Mappers/TransactionMapper.php
- src/PurchaseTransactionLine.php
- src/SalesTransactionLine.php
- src/Transactions/TransactionLineFields/MatchDateField.php
- tests/IntegrationTests/PurchaseTransactionIntegrationTest.php
- tests/IntegrationTests/resources/purchaseTransactionGetResponse.xml
The value of `<matchdate>` is currently not retrievable from transactions, this PR aims to fix this.
This PR adds `getMatchDate()` and `setMatchDate()` to `PurchaseTransactionLine` and `SalesTransactionLine`*
This matchDate attribute may only be set on total lines (per [documentation](https://accounting2.twinfield.com/webservices/documentation/#/ApiReference/PurchaseTransactions)), and will throw if an attempt is made for it to be set on another line type.
*The documentation only mentions `<matchdate>` for the purchase transaction, however testing the actual API revealed that this element is also present in get responses on sales transactions.
> Add support for transaction line match date

- src/ApiConnectors/LedgerAccountApiConnector.php
- src/LedgerAccount.php
I've added the Ledger Account connector, based on the documentation: https://accounting.twinfield.com/webservices/documentation/#/ApiReference/Masters/BalanceSheets
The code is similar/identical to that of the VatCodeApiConnector.
We require this functionality for a project.
> feat: added list all ledger accounts connector

- src/Account.php
- src/ApiConnectors/VatCodeApiConnector.php
- src/Mappers/VatMapper.php
- src/Request/Read/VatCode.php
- src/VatCodeDetail.php
- src/VatCodePercentage.php
- tests/IntegrationTests/VatCodeIntegrationTest.php
- tests/IntegrationTests/resources/vatCodeGetResponse.xml
For a project I'm working on I need the ability to lookup the VAT percentages. I've tried matching the coding style as much as possible, but it might be off in some places.
Also, I'm not quite sure about the naming I used for the objects as `VatCode` (less detailed) was already used for the `listAll` method on the connector.
Happy to change anything, let me know!
> Adding ability to fetch VAT code details

- tests/IntegrationTests/resources/invoiceSendRequest.xml
When preparing a different pull request I noticed an unrelated test was failing. The changes from pull request #206 add the `paymentmethod` element to the `InvoiceDocument`, but the example xml file used in the tests was not updated yet.
> Adding missing element to invoiceSendRequest.xml

- src/DomDocuments/TransactionsDocument.php
- tests/UnitTests/DomDocuments/TransactionsDocumentUnitTest.php
I ran into a TypeError while omitting dim1 field on a transaction line with type VAT. According to the [Twinfield documentation](https://accounting.twinfield.com/webservices/documentation/#/ApiReference/Transactions/SalesTransactions) the dim1 field can be empty for these transaction lines.
> If line type = `vat` the VAT balance account. When an empty dim1 is entered, by default the general ledger account will be taken as entered at the VAT code in Twinfield.
This seems to be true for all transaction types which allow VAT lines.
> Handle TypeError when dim1 is omitted on VAT lines

- composer.json
- tests/UnitTests/ApiConnectors/BaseApiConnectorTest.php
In order to support psr/log version 2 & 3 we need to define the versions in composer.json file. Verified that psr/log is backward compatible.
> Added psr/log version 2.0 || 3.0 to the composer.json

- readme.md
- src/Secure/OpenIdConnectAuthentication.php
- tests/UnitTests/Secure/OpenIdConnectionAuthenticationTest.php
Hi, I've created a pull request allowing people to:
1. Setup a connection with an existing access token object
2. Add a custom callback to be called when a token is refresh, to process the token.
There's already a similar idea in: https://github.com/php-twinfield/twinfield/pull/144#issuecomment-1361121363
That PR is fairly old and did not seem to be very active. Also it included some other unrelated improvements, that might makes this hard to merge to master.
The code has some breaking changes in case someone is overriding `src/Secure/OpenIdConnectAuthentication.php` `login()` or `validateToken()`
- Allow setting an AccessToken object, through constructor or setter
-  This prevents unnecessary token requests in case the access token is valid.
- Only validate the token on login when:
- The …
> Support existing accessToken on OpenIdConnectAuthentication

- src/DomDocuments/TransactionsDocument.php
- tests/UnitTests/DomDocuments/TransactionsDocumentUnitTest.php
Fixes the issue as described by @edwin-easytrans in https://github.com/php-twinfield/twinfield/pull/199#issuecomment-1474785075 by limiting the scope of the earlier change to only apply to VAT lines.
> Only skip setting dim1 on transaction lines when the line is of type VAT

- src/BaseTransactionLine.php
- src/Mappers/TransactionMapper.php
- src/Transactions/MatchLine.php
- src/Transactions/MatchSet.php
- tests/IntegrationTests/PurchaseTransactionIntegrationTest.php
- tests/IntegrationTests/resources/purchaseTransactionGetResponse.xml
This includes all types of transactions except for banktransactions
Bump supported PHP version to 8.0
Fix a bunch of deprecated warnings in tests
Bump eloquent/liberate library to 3.0 version to support php 8.2
> Add support for matches field on transactions

- src/SalesTransactionLine.php
Apparently all fields on salestransactionline that are listed in the documentation as 'total' only, can also be set on 'detail' if the line has a project.
> Fix more Project salestransactionline issues

- composer.json
- phpstan.neon
- tests/Dummy/StringStream.php
- tests/UnitTests/Secure/Provider/OAuthProviderTest.php
By loosening the constraints consumers will be able to upgrade their `psr/http-message` constraints too.
This change is untested ❗
> Loosen `psr/http-message` version to allow `^2.0`

- src/DomDocuments/ArticlesDocument.php
- src/DomDocuments/CustomersDocument.php
- src/DomDocuments/InvoicesDocument.php
- src/DomDocuments/SuppliersDocument.php
- src/DomDocuments/TransactionsDocument.php
Fix for messages:
Deprecated: DOMDocument::createTextNode(): Passing null to parameter #1 ($data) of type string is deprecated
> Fix: added empty string instead of null
